Maincollections
6ig6or6/trainee-tasks pull request #2
Opened 2022-10-21 13:00 UTC by 6ig6or6

All collections from the task are implemented

2022-10-21 14:13 UTC, ALnOUA requested changes

2022-10-21 14:13 UTC, ALnOUA commented on src/main/java/org/example/maincollections/map/TreeMap.java
> +    }
Let`s try to do it more readable. Try to use predicates with understandable naming and split it on separate private methods

2022-10-21 14:13 UTC, ALnOUA commented on src/main/java/org/example/maincollections/map/TreeMap.java
> +    }
The same, let`s try to use predicates + private methods

2022-10-21 14:13 UTC, ALnOUA commented on src/test/java/org/example/maincollections/LinkedListTest.java
> +    void contains() {
Naming of test methods should be more informative. 
See https://dzone.com/articles/7-popular-unit-test-naming and https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html
Also, there are a lot of other strategies, but common point is informative naming
For example, it could be whenContainsWithRequiredObjectThenSuccess or something like this

2022-10-22 16:07 UTC, ALnOUA requested changes

2022-10-22 16:07 UTC, ALnOUA commented on src/main/java/org/example/maincollections/map/TreeMap.java
>          V oldValue = p.value;
if (p == null) {
 return null;
}

2022-10-22 16:07 UTC, ALnOUA commented on src/main/java/org/example/maincollections/map/TreeMap.java
>      }
The name of the method already indicates a violation of the  SOLID`s S principle
try to declare one more additional method of  unlinking

2022-10-22 16:54 UTC, 6ig6or6 commented on src/main/java/org/example/maincollections/map/TreeMap.java
>          V oldValue = p.value;
I noticed this right after I clicked re-request :)

2022-10-23 13:28 UTC, ALnOUA approved these changes

2022-10-24 10:26 UTC, merged